#!/bin/bash
#
# chkconfig: - 20 80
# /etc/rc.d/init.d/talookd
# description: System stats web ui
# processname: talookd
# config: /etc/talook/config.json
# pidfile: /var/run/talookd.pid
#
#
# Source function library

. /etc/rc.d/init.d/functions

app_name="talookd"
app=/usr/bin/talook-server
OPTIONS="--listen 0.0.0.0 --port 8080 --config /etc/talook/config.json"

# If there is a sysconfig config then source it in and override OPTIONS
SYSCONF_FILE=/etc/sysconfig/talookd.conf
[ -f ${SYSCONF_FILE} ] && . ${SYSCONF_FILE}

pidfile="/var/run/talookd.pid"

RETVAL=0

start() {
        echo -n $"Starting $app_name: "

        pgrep -f ${app} > /dev/null
        RUNNING=$?
        if [ $RUNNING -eq 0 ]; then     
            echo "[FAILED]"
            echo    
            echo "Reason: ${app_name} is already running."
            RETVAL=1
            exit 1;
        fi

        daemon --user talookd --pidfile=${pidfile} "${app} ${OPTIONS} &"
        pgrep -f ${app} > ${pidfile}
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/talookd
        
}


stop() {
        echo -n $"Stopping $app_name: "
        kill `cat ${pidfile}`

        RETVAL=$?
        echo
        #[ $RETVAL = 0 ] && rm -f ${pidfile}
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/talookd
}

case "$1" in
	start)
	        start
	;;
	stop)
	        stop
	;;
	status)
         	status -p ${pidfile} $app
                RETVAL=$?
	;;
	restart)
	        stop
	        start
	;;
	*)
		echo "Usage: talookd {start|stop|status|restart}"
		exit 1
	;;
esac
